//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AssignmentModelContainer : DbContext
    {
        public AssignmentModelContainer()
            : base("name=AssignmentModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Organiser> Organisers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Event> Events { get; set; }
    }
}
