//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public string userEmail { get; set; }
        public string eventTime { get; set; }
        public System.DateTime eventDate { get; set; }
        public string eventName { get; set; }
        public System.DateTime bookingDate { get; set; }
        public int seatCount { get; set; }
    
        public virtual User User { get; set; }
        public virtual Event Event { get; set; }
    }
}
